name: Newman run

on:
  push:
    branches:
      - main 

jobs:
  newman:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      # Criar diret贸rio para armazenar o relat贸rio
      - name: Create dir for reports
        run: mkdir -p newman/reports

      # Instalar Newman e o Reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Rodar o Newman e gerar o relat贸rio
      - name: Run Tests with Newman
        run: newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r htmlextra --reporter-htmlextra-export newman/reports/report.html

      # Fazer upload do relat贸rio gerado
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with: 
          name: reports
          path: newman/reports/report.html
